version: "3"


networks:
  myrsshub:


# ---------------------------------------- nginx ---------------------------------------- #
services:
  nginx:
    image: nginx:stable
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/nginx.sh:/nginx.sh
      - ./nginx/vhost:/etc/nginx/conf.d/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - PROTOCOL=https
      - RSSHUB_DOMAIN={DOMAIN}
      - RSSHUB_DOAMIN_CERT={CERT}
      - RSSHUB_DOMAIN_KEY={KEY}
    networks:
      - myrsshub
    depends_on:
      - rsshub


# ---------------------------------------- rsshub ---------------------------------------- #
  rsshub:
    image: diygod/rsshub:chromium-bundled
    restart: always
    ports:
      - 1200:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    depends_on:
      - redis
    networks:
      - myrsshub
    

  redis:
    image: redis:alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis-data:/data
    networks:
      - myrsshub
